title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!

url: https://temp.simple-hope.art

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
